// Generated by gencpp from file new_msgs/Armor.msg
// DO NOT EDIT!


#ifndef NEW_MSGS_MESSAGE_ARMOR_H
#define NEW_MSGS_MESSAGE_ARMOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_msgs
{
template <class ContainerAllocator>
struct Armor_
{
  typedef Armor_<ContainerAllocator> Type;

  Armor_()
    : grade(0)
    , id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Armor_(const ContainerAllocator& _alloc)
    : grade(0)
    , id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _grade_type;
  _grade_type grade;

   typedef int64_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::new_msgs::Armor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_msgs::Armor_<ContainerAllocator> const> ConstPtr;

}; // struct Armor_

typedef ::new_msgs::Armor_<std::allocator<void> > Armor;

typedef boost::shared_ptr< ::new_msgs::Armor > ArmorPtr;
typedef boost::shared_ptr< ::new_msgs::Armor const> ArmorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_msgs::Armor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_msgs::Armor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::new_msgs::Armor_<ContainerAllocator1> & lhs, const ::new_msgs::Armor_<ContainerAllocator2> & rhs)
{
  return lhs.grade == rhs.grade &&
    lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::new_msgs::Armor_<ContainerAllocator1> & lhs, const ::new_msgs::Armor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace new_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::new_msgs::Armor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_msgs::Armor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_msgs::Armor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_msgs::Armor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_msgs::Armor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_msgs::Armor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_msgs::Armor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f01bc42540f7302c184397f596483711";
  }

  static const char* value(const ::new_msgs::Armor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf01bc42540f7302cULL;
  static const uint64_t static_value2 = 0x184397f596483711ULL;
};

template<class ContainerAllocator>
struct DataType< ::new_msgs::Armor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_msgs/Armor";
  }

  static const char* value(const ::new_msgs::Armor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_msgs::Armor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 grade\n"
"int64 id\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::new_msgs::Armor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_msgs::Armor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grade);
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Armor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_msgs::Armor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_msgs::Armor_<ContainerAllocator>& v)
  {
    s << indent << "grade: ";
    Printer<int64_t>::stream(s, indent + "  ", v.grade);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_MSGS_MESSAGE_ARMOR_H
